server:
  port: 9669

zuul:
  routes:
    get-fortune:
      serviceId: fortune
      path: /get-fortune
      # do not pass sensitive headers to downstream services
      sensitiveHeaders: Cookie,Set-Cookie,Authorization

ribbon:
  eureka:
    enabled: false
  # Obsolete option (Apache HttpClient by default), but without this Ribbon doesn't retry against another instances
  restclient:
    enabled: true

hystrix:
  command:
    fortune:
      circuitBreaker:
        sleepWindowInMilliseconds: 3000
        errorThresholdPercentage: 90
      execution:
        isolation:
          thread:
            # should be little bit bigger than Ribbon's ConnectTimeout + ReadTimeout
            timeoutInMilliseconds: 5500

fortune:
  ribbon:
    OkToRetryOnAllOperations: false
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    listOfServers: ${LIST_OF_SERVERS}
    ConnectTimeout: 500
    ReadTimeout: 4500
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1000
    retryableStatusCodes: 404,502,503,504